Repository lumiastream/lumia-types, pull requests merged in 2025-09, with the labels that each got.

#89 fix: add ai prompt variable
  src/variables.types.ts
Labels: bug

#91 chore: add descriptions for alert variations equal string
  package-lock.json
  package.json
  src/alert.types.ts
Labels: chore

#93 feat: youtube gift members and sessions alerts
  docs/custom-overlays/custom-overlays.d.ts
  package-lock.json
  package.json
  src/activity.types.ts
  src/alert.types.ts
  src/variables.types.ts
  src/youtube_superstickers.ts
Labels: enhancement

#94 feat: meld scene switch and vertical scene switch
  docs/custom-overlays/custom-overlays.d.ts
  package-lock.json
  package.json
  src/activity.types.ts
  src/alert.types.ts
  src/variables.types.ts
Labels: enhancement
